CREATE OR REPLACE STORAGE INTEGRATION s3_int_msrisk
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = ROLE_ARN
STORAGE_ALLOWED_LOCATIONS = ('s3://ms-market-risk-bucket/')
STORAGE_AWS_EXTERNAL_ID = EXTERNAL_ID;
